## where to store your database, default is your system data directory
## linux/mac: ~/.local/share/atuin/history.db
## windows: %USERPROFILE%/.local/share/atuin/history.db
# db_path = "~/.history.db"

## where to store your encryption key, default is your system data directory
## linux/mac: ~/.local/share/atuin/key
## windows: %USERPROFILE%/.local/share/atuin/key
# key_path = "~/.key"

## where to store your auth session token, default is your system data directory
## linux/mac: ~/.local/share/atuin/session
## windows: %USERPROFILE%/.local/share/atuin/session
# session_path = "~/.session"

## date format used, either "us" or "uk"
dialect = "uk"

## enable or disable automatic sync
auto_sync = true

## enable or disable automatic update checks
update_check = true

## which search mode to use
## possible values: prefix, fulltext, fuzzy, skim
search_mode = "skim"

## which filter mode to use by default
## possible values: "global", "host", "session", "directory", "workspace"
filter_mode = "global"

## which search mode to use when atuin is invoked from a shell up-key binding
## the accepted values are identical to those of "search_mode"
search_mode_shell_up_key_binding = "skim"

## which filter mode to use when atuin is invoked from a shell up-key binding
## the accepted values are identical to those of "filter_mode"
filter_mode_shell_up_key_binding = "global"

## which style to use
## possible values: auto, full, compact
style = "compact"

## the maximum number of lines the interface should take up
## set it to 0 to always go full screen
inline_height = 0

## Invert the UI - put the search bar at the top , Default to `false`
invert = false

## enable or disable showing a preview of the selected command
show_preview = true

## what to do when the escape key is pressed when searching
## possible values: return-original, return-query
exit_mode = "return-original"

## Defaults to true. If enabled, upon hitting enter Atuin will immediately execute the command. Press tab to return to the shell and edit.
enter_accept = false

## Defaults to "emacs". This specifies the keymap on the startup of `atuin search`
keymap_mode = "emacs"

## Set this to true and Atuin will minimize motion in the UI
prefers_reduced_motion = false

[sync]
## Enable sync v2 by default
records = true

[keys]
## Defaults to true. If disabled, using the up/down key won't exit the TUI when scrolled past the first/last entry.
scroll_exits = false

## Defaults to true. The left arrow key will exit the TUI when scrolling before the first character
exit_past_line_start = true

## Defaults to true. The right arrow key performs the same functionality as Tab
accept_past_line_end = true

common_prefix = ["sudo", "doas"]
common_subcommands = ["--help", "-h", "--version", "-V"]

history_filter=[]